In [47]:
import numpy as np
import pandas as pd

In [48]:
npz = np.load('PEMS_04/pems04.npz')

In [49]:
df= pd.DataFrame(npz)

In [50]:
data = npz['data']
print(data)
print(data.shape)

[[[6.20e+01 7.70e-03 6.79e+01]
  [5.60e+01 1.12e-02 6.84e+01]
  [9.00e+01 1.43e-02 6.82e+01]
  ...
  [5.60e+01 9.80e-03 6.74e+01]
  [4.80e+01 7.80e-03 6.95e+01]
  [3.80e+01 9.40e-03 6.82e+01]]

 [[6.10e+01 7.40e-03 6.73e+01]
  [4.00e+01 8.00e-03 6.86e+01]
  [9.40e+01 1.56e-02 6.78e+01]
  ...
  [5.10e+01 9.40e-03 6.60e+01]
  [3.00e+01 5.00e-03 6.91e+01]
  [3.50e+01 8.50e-03 6.88e+01]]

 [[7.10e+01 9.30e-03 6.84e+01]
  [2.80e+01 6.80e-03 6.74e+01]
  [7.90e+01 1.22e-02 6.87e+01]
  ...
  [6.70e+01 1.17e-02 6.67e+01]
  [3.10e+01 5.30e-03 6.88e+01]
  [4.50e+01 1.11e-02 6.95e+01]]

 ...

 [[6.60e+01 8.90e-03 6.78e+01]
  [7.60e+01 1.58e-02 6.59e+01]
  [7.70e+01 1.82e-02 6.40e+01]
  ...
  [8.50e+01 1.45e-02 6.73e+01]
  [5.80e+01 1.00e-02 6.93e+01]
  [5.70e+01 1.66e-02 6.78e+01]]

 [[7.70e+01 1.03e-02 6.74e+01]
  [7.30e+01 1.66e-02 6.58e+01]
  [9.60e+01 2.01e-02 6.31e+01]
  ...
  [6.90e+01 1.20e-02 6.72e+01]
  [5.20e+01 8.70e-03 6.93e+01]
  [4.30e+01 1.18e-02 6.91e+01]]

 [[7.40e+01 9.80e-03 6.7

In [51]:
data.shape

(16992, 307, 3)

In [52]:
#arr = np.array([[0.0 for _ in range(data.shape[0])] for i in range(data.shape[1])], dtype=float)
arr = np.zeros((data.shape[1], data.shape[0]), dtype=float, order = 'F')
arr

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [53]:
arr.shape

(307, 16992)

In [54]:
data[0].shape

(307, 3)

In [55]:
len(data[0][0])

3

In [56]:
for time in range(len(data)):
    for sensor in range(len(data[0])):
        arr[sensor][time] = data[time][sensor][2]
    
arr

array([[67.9, 67.3, 68.4, ..., 67.8, 67.4, 67. ],
       [68.4, 68.6, 67.4, ..., 65.9, 65.8, 68.7],
       [68.2, 67.8, 68.7, ..., 64. , 63.1, 65.2],
       ...,
       [67.4, 66. , 66.7, ..., 67.3, 67.2, 67. ],
       [69.5, 69.1, 68.8, ..., 69.3, 69.3, 69.6],
       [68.2, 68.8, 69.5, ..., 67.8, 69.1, 69.7]])

In [57]:
df = pd.DataFrame(arr)
df

0      1      2      3      4      5      6      7      8      9      \
0     67.9   67.3   68.4   67.8   67.4   67.6   67.0   66.1   66.3   65.7   
1     68.4   68.6   67.4   69.5   68.1   69.0   67.0   64.8   63.5   64.0   
2     68.2   67.8   68.7   68.9   67.3   67.3   67.8   68.5   68.0   67.1   
3     66.3   65.7   66.6   66.8   67.0   66.9   66.5   66.3   66.4   65.9   
4     65.4   66.8   67.2   66.3   68.4   67.1   66.8   67.3   67.0   67.6   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
302   69.6   67.7   69.0   68.7   69.1   67.5   66.1   66.2   67.7   67.2   
303   68.6   68.7   68.3   68.6   68.1   68.0   68.0   67.2   66.9   67.6   
304   67.4   66.0   66.7   67.8   67.9   66.6   66.6   66.8   66.1   65.3   
305   69.5   69.1   68.8   68.5   67.9   68.7   68.5   68.7   68.5   68.6   
306   68.2   68.8   69.5   68.8   68.7   68.9   67.9   67.8   68.3   67.3   

     ...  16982  16983  16984  16985  16986  16987  16988  16989  16990  16991  
0    ...   66.8   65.4   65.5   66.2   66.6   67.8   67.8   67.8   67.4   67.0  
1    ...   62.0   64.1   63.9   65.0   46.9   57.7   61.8   65.9   65.8   68.7  
2    ...   65.4   62.9   62.9   63.3   64.2   64.9   65.4   64.0   63.1   65.2  
3    ...   67.2   67.2   67.0   67.0   67.2   67.1   67.2   67.2   67.1   67.0  
4    ...   67.5   67.0   67.4   67.3   65.9   65.2   65.8   63.7   67.0   65.4  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
302  ...   66.9   65.6   64.1   64.2   63.6   65.3   65.7   66.8   66.0   67.5  
303  ...   67.8   68.4   67.5   66.4   65.9   66.4   67.1   66.7   66.9   67.7  
304  ...   66.3   66.3   66.8   66.8   66.9   66.7   67.4   67.3   67.2   67.0  
305  ...   69.5   68.2   68.1   68.3   69.7   68.7   68.4   69.3   69.3   69.6  
306  ...   70.0   68.0   68.1   65.7   67.4   69.4   68.7   67.8   69.1   69.7  

[307 rows x 16992 columns]

In [58]:
df.to_csv("PEMS_O4/PEMS_O4.csv", index=False, header=False)

GCN___DATA PREPROCESSING
_______________________________________________________________________________________

In [59]:
no_of_sensors = data.shape[1]
no_of_sensors

307

In [60]:
data = pd.read_csv("PEMS_04/distance.csv")


In [61]:
arr = np.zeros((no_of_sensors, no_of_sensors), dtype=float)

In [62]:
arr.shape

(307, 307)

In [63]:
for i in range(no_of_sensors):
    if arr[data['from'][i]][data['to'][i]] > 0:
        print(f"duplicate entry found at {i} {arr[data['from'][i]][data['to'][i]]}")
    arr[data['from'][i]][data['to'][i]] = data['cost'][i]/1000
    arr[data['to'][i]][data['from'][i]] = data['cost'][i]/1000

arr

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [64]:
dt = pd.DataFrame(arr)

In [65]:
dt

0    1    2    3    4    5    6    7    8    9    ...  297  298  299  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
302  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
303  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
304  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
305  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
306  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     300  301  302  303  304  305  306  
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
302  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
303  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
304  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
305  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
306  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[307 rows x 307 columns]

In [66]:
dt.to_csv('PEMS_O4/PEMS_04_GCN.csv',index=False, header=False)